### ISSUE TITLE
Cache `uidNumber` call

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/gulp-chown#1]
It spawns a child process which is slow. The result should be cached for the lifetime of the process in case a user uses it multiple times.

https://github.com/sindresorhus/gulp-chown/blob/46a77e68572a54aa06d4d30c453b9c4b4ee920a7/index.js#L30

**Comment by kevva** [comment]
Maybe store it in a environment variable and reset it upon `process.exit`?

**Comment by sindresorhus** [comment]
No, you can just have a variable here: https://github.com/sindresorhus/gulp-chown/blob/46a77e68572a54aa06d4d30c453b9c4b4ee920a7/index.js#L5 since modules are cached ;)

**Comment by kevva** [comment]
Why are these lines here https://github.com/sindresorhus/gulp-chown/blob/46a77e68572a54aa06d4d30c453b9c4b4ee920a7/index.js#L42-L43 :p?

**Comment by sindresorhus** [comment]
It's so it's only run on the first file. So it's some kind of cache. The point of this issue is to cache the `uidNumber` between different streams as long as the process runs.

**Comment by kevva** [comment]
Yeah, thought they was never called.
