### ISSUE TITLE
Does not work with gulp.dest

### ISSUE THREAD

**Issue by dvtylr** [sindresorhus/gulp-chown#3]
While the plug-in does change the file.stat.uid that information is not used by gulp.dest so does not seem to have any effect on the file ownership on writing.  At a minimum the example should be changed to reflect this although I am not sure how the plug-in would be used without gulp.dest support.

**Comment by sindresorhus** [comment]
Well, `gulp.dest` should use that. If it doesn't, open an issue on https://github.com/wearefractal/vinyl-fs ;)

**Comment by c0d3rman** [comment]
This is actually an issue you should resolve, either by talking with the vinyl-fs people or changing your module. Right now, gulp-chown is useless as it doesn't actually chown anything. (I used almost exactly your example and it didn't work.) Do you have a working example of using it? Perhaps I'm doing something wrong on my end.
